# Generated by Django 4.1.7 on 2023-03-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='carrier_plan_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='color',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.fabricante', unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='model',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
