# Generated by Django 4.1.7 on 2023-03-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_produtos_carrier_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loja.fabricante'),
        ),
    ]
